
---
owner: eddiesarevalo
repo: TrekPatrol
sites:
  - name: Trek Home site trek.nasa.gov
    url: https://trek.nasa.gov/?cloudfront=no
    assignees:
      - eddiesarevalo
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

  - name: Mars Trek
    url: https://trek.nasa.gov/mars&cloudfront=no
    assignees:
      - eddiesarevalo
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

  - name: Moon Trek
    url: https://trek.nasa.gov/moon&cloudfront=no
    assignees:
      - eddiesarevalo
    maxResponseTime: 5000

  - name: Vesta Trek
    url: https://trek.nasa.gov/vesta&cloudfront=no
    assignees:
      - eddiesarevalo
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

  - name: Ceres Trek
    url: https://trek.nasa.gov/ceres&cloudfront=no
    assignees:
      - eddiesarevalo
    maxResponseTime: 5000

  - name: Callisto Trek
    url: https://trek.nasa.gov/callisto&cloudfront=no
    assignees:
      - eddiesarevalo
    maxResponseTime: 5000

  - name: Titan Trek
    url: https://trek.nasa.gov/titan&cloudfront=no
    assignees:
      - eddiesarevalo
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

  - name: Phobos Trek
    url: https://trek.nasa.gov/phobos&cloudfront=no
    assignees:
      - eddiesarevalo
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

status-website:
  baseUrl: /TrekPatrol
  name: Trek Patrol
  introTitle: "**Trek Patrol** is a monitoring system for the Solar System Trek Portals"
  introMessage: >
    The status of various Solar System Trek Portal sites, APIs, and
    other network endpoints is presented below.
  theme: light
  navbar:
    - title: Status
      href: /
    - title: SSTP
      href: https://trek.nasa.gov
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
delay: 2000
skipDescriptionUpdate: true
skipTopicsUpdate: true
...